### ISSUE TITLE
The UI in version 3.x is to minimalistic for pre-3.x-players

### ISSUE THREAD

**Issue by vinzenz-fischer** [raiguard/RateCalculator#100]
The new UI of the Rate Calculator mod is too minimalist and too hard to read for players, that are used to the traditional UI.
Many features I and friends of mine used regularly are not included anymore or hidden until hovered over the appropriate icon.

Please add an option to enable players to use the pre-3.x UI.

Trying to load a level with the 2.4.8 version of this mod causes a unrecoverable error and is thus not a viable option for players.

This mod is by far my most used tool in factorio and I am very thankful for it to exist.

**Comment by raiguard** [comment]
What features are missing? All of the rate information should still exist in the tooltips.

The reason I simplified the UI was because after not playing the game for almost two years, I tried to use RC and found it difficult to read my own UI. It's not very intuitive at all for new players. The new UI is much clearer in what it is telling you, and it's super easy to spot which materials are the bottleneck.

Reimplementing the old UI might be possible, but would require a completely separate GUI update loop that would require maintenance. I encourage you to give the new UI a chance.

**Comment by vinzenz-fischer** [comment]
Apologies for the bad formulation. I couldn't tell whether features are missing or I just couldn't find them.

After a few hours of playing with the new UI I could figure it all out (I think).
Guess I just was pissed off, that it changed so drastically from one factorio session to another.

**Comment by raiguard** [comment]
Yeah, I can understand the frustration, sorry. I also may not have explained the new UI well enough in the readme. I'll see if I can improve the explanation.
