### ISSUE TITLE
I would like an option to have the old interface back that didn't hide info inside tooltips

### ISSUE THREAD

**Issue by Mohaim-1** [raiguard/RateCalculator#108]
For me, the new version's redesigned interface is less useful/convenient than before. Previously, all info was displayed all the time on the main window and not hidden inside tooltips, so it was easier to glance around and find the info I wanted without having to slowly move the mouse from one product to another and pausing, looking at each tooltip one at a time.

The interface seems to makes assumptions about info I would always need, which is displayed in the main window, and info I would rarely need, which is hidden in tooltips, and those assumptions are often incorrect.

For example, the mod now makes assumptions about what's a product and what's an ingredient for that product, which isn't always correct. For example, I sometimes want to view the info for all green, red, and blue chips at once, and now I can't find out raw output of green or red chips at a glance because they are assumed to always be consumed by blue chips, and I only care about surplus, which is not the case. Sometimes they are consumed, and sometimes they aren't. Now, to find the info I need I have to use the tooltips, and I can't view that info for green and red chips at the same time.

I liked when all the info I could want was displayed in the main window, so I could find any of the info I wanted instantly, rather than having to dig around in the tooltips and also not being able to view the info that's in the tooltips for multiple products at the same time.

**Comment by raiguard** [comment]
I'm sorry that you don't like the new interface. I redesigned the mod because the old interface, while intuitive for those who were used to it, was very confusing for new and returning users. The new UI throws less information in your face and organizes it better by separating it into ingredients, products, and intermediates.

I'm not going to be bringing back the old UI, but you are free to post a fork on the mod portal if you wish to continue to use it. There were many more changes than just a UI refresh - this was a complete rewrite of the mod.

**Comment by Mikerosoft666** [comment]
I'm sure that the new interface will do a good job as the old one did.  I just need to get used to it.  Wish there had of been a way to keep it.  Rename the old Mod maybe ?

It took me awhile to understand it but once I did I couldn't do anything effectively without it.  So kudos for the work you have done on it.

**Comment by raiguard** [comment]
It won't be identical to the old one, but enough people have bemoaned the loss of the detailed info that it's obvious that I need to bring back an "advanced" display mode. I apologize for being stubborn. The simplified display is way easier to understand for newcomers but it's undoubtedly less powerful than the previous design.

**Comment by Tsunayoshi** [comment]
I am sorry to say but actually i decided to use the Rate Calc because i did not like the MaxRate Calc Mods interface. Now they the same. I came back to this game after a 10 month break and can say, the new interface is not user friendly. Important information are hidden in tooltips and not comparable this way. Products information (right side) are not in columns under each other and soooo hard to read if u want to compare 2 lines.
Yes the Interface is simpler for new ppl BUT u have to judge your mod users better! This are ppl who want to minmax, So we WANT the detail information.

I hope someone forks the mod on the 2.x status because at this state i will just build without using it and not care about minmax anymore.

As Example:
![image](https://user-images.githubusercontent.com/5128201/236622155-1d0a8bd8-9bc1-4428-a95f-2cf2642173cd.png)

Why is there on heavy fuel a refinery (no pic of a chemical plant!) telling me it consume too much by -7.17 per refinery(!)., and end up be -29.6. If something consumes it then its chemical plants. Refinery produce things!.

The Information i need to judge if i need more or less buildings are hidden in the tooltip:
![image](https://user-images.githubusercontent.com/5128201/236622230-d94ad20e-8975-4bdd-9c7f-7991aa107ce1.png)

This does not make any sense to me! Also the tooltip is so unbelievable hard to compare they information because they not under each other. For me this interface is a step backwards.

**Comment by raiguard** [comment]
The interface shows how many machines produce each thing (3 refineries producing heavy oil), and how many more machines you need producing heavy oil you need to balance the rates (7.17). However, in this case, you want more chemical plants, so what you should do is shift+select a chemical plant until the net rate turns green and you can then see how many you need.

The new design is not universally bad, there are many people who love it and many who hate it. A common theme appears to be that people don't know you can shift+select to append the existing selection, and shift+right select to remove from it. The intended way to use it is to append the selection until all of the net rates turn green and then you know how many machines producing each thing that you need.

**Comment by raiguard** [comment]
I'm going to close this in favor of #111, since I'm not bringing back the old interface, the other issue is more accurate.
